---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pivotalpa/angular-cli

inputs:
- name: marcus-angular

outputs:
- name: compiled-marcus-angular

run:
  path: sh
  args:
    - -exc
    - |
      cd marcus-angular
      npm install
      ng build --prod --aot
      cd dist && touch Staticfile
      echo \"pushstate:enabled\" > Staticfile
      cd ..
      cp -r dist/* ../compiled-marcus-angular/
