---
platform: linux

inputs:
- name: marcus-angular

run:
  path: marcus-angular/pipelines/tasks/run-build.sh
  args:
    - -exc
    - |
      ng build --prod --aot
      cd dist && touch Staticfile
      echo 'pushstate: enabled' > Staticfile
