---
platform: linux

image_resource:
  type: docker-image
  source: {repository: ubuntu}

inputs:
- name: marcus-angular

run:
  path: chmod
  args:
    - +x marcus-angular/pipelines/tasks/run-build.sh

run:
  path: marcus-angular/pipelines/tasks/run-build.sh
  args:
    - -exc
