---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pivotalpa/angular-cli

inputs:
- name: marcus-angular

run:
  path: sh
  args:
    - -exc
    - |
      chmod 755 ./mg-angular/pipelines/tasks/run-build.sh
      ./mg-angular/pipelines/tasks/run-build.sh
