---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: weboaks/node-karma-protractor-chrome
    tag: "latest"

inputs:
- name: marcus-angular

run:
  path: marcus-angular/pipelines/tasks/run-build.sh
