---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pivotalpa/angular-cli

inputs:
- name: marcus-angular

run:
  path: marcus-angular/marcus-angular/pipelines/tasks/run-build.sh
  args:
    - -exc
